name: Build Piko patches

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: read

jobs:
  build:
    name: Build Piko patches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v3

      - name: Build with Gradle
        run: ./gradlew clean buildAndroid

      - name: Upload patch files
        uses: actions/upload-artifact@v4
        with:
          name: piko-patches
          path: patches/build/libs/*.mpp
          if-no-files-found: error
